[unstable]
build-std-features = ["compiler-builtins-mem"] # 提供基础的内存操作函数
build-std = ["core", "compiler_builtins"] # 重新编译core, 因为我们没有core

[build]
target = "x86_64-blog_os.json" # 目标系统描述

[target.'cfg(target_os = "none")']
runner = "bootimage runner" # 使用 carog run 来运行